bind = "unix:/home/prospa/portfolio/portfolio.sock"
user= "ubuntu"
group = "ubuntu"
umask = 0o007
workers = 2
worker_class = "sync"
worker_connections = 1000
max_requests = 1000
max_requests_jitter = 100
timeout = 30
keepalive = 2
preload_app = True
